//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShelfLifeApp {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShelfLifeApp.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string AddEditPageButton1 {
            get {
                return ResourceManager.GetString("AddEditPageButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growers.
        /// </summary>
        internal static string AddEditPageEntry1 {
            get {
                return ResourceManager.GetString("AddEditPageEntry1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet #.
        /// </summary>
        internal static string AddEditPageEntry2 {
            get {
                return ResourceManager.GetString("AddEditPageEntry2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COO.
        /// </summary>
        internal static string AddEditPagePicker1 {
            get {
                return ResourceManager.GetString("AddEditPagePicker1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packers.
        /// </summary>
        internal static string AddEditPagePicker2 {
            get {
                return ResourceManager.GetString("AddEditPagePicker2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        internal static string AddEditPagePicker3 {
            get {
                return ResourceManager.GetString("AddEditPagePicker3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string AddEditPagePicker4 {
            get {
                return ResourceManager.GetString("AddEditPagePicker4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample#.
        /// </summary>
        internal static string AddEditPageSampleNumber {
            get {
                return ResourceManager.GetString("AddEditPageSampleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sample.
        /// </summary>
        internal static string AddEditPageTitle {
            get {
                return ResourceManager.GetString("AddEditPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start New Sample.
        /// </summary>
        internal static string HomePageButton1 {
            get {
                return ResourceManager.GetString("HomePageButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to California Inspections.
        /// </summary>
        internal static string HomePageInspected1 {
            get {
                return ResourceManager.GetString("HomePageInspected1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexico Inspections.
        /// </summary>
        internal static string HomePageInspected2 {
            get {
                return ResourceManager.GetString("HomePageInspected2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peru Inspections.
        /// </summary>
        internal static string HomePageInspected3 {
            get {
                return ResourceManager.GetString("HomePageInspected3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissionPro.
        /// </summary>
        internal static string HomeTabbedPageTitle {
            get {
                return ResourceManager.GetString("HomeTabbedPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string HomeTabbedPageToolbarItem1 {
            get {
                return ResourceManager.GetString("HomeTabbedPageToolbarItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        internal static string HomeTabbedPageToolbarItem2 {
            get {
                return ResourceManager.GetString("HomeTabbedPageToolbarItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age:.
        /// </summary>
        internal static string InspectableItemAge {
            get {
                return ResourceManager.GetString("InspectableItemAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string InspectableItemAlertMsg1 {
            get {
                return ResourceManager.GetString("InspectableItemAlertMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty values or Dropdowns not selected.
        /// </summary>
        internal static string InspectableItemAlertMsg2 {
            get {
                return ResourceManager.GetString("InspectableItemAlertMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string InspectableItemAlertMsg3 {
            get {
                return ResourceManager.GetString("InspectableItemAlertMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string InspectableItemColor {
            get {
                return ResourceManager.GetString("InspectableItemColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string InspectableItemComments {
            get {
                return ResourceManager.GetString("InspectableItemComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string InspectableItemCut {
            get {
                return ResourceManager.GetString("InspectableItemCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defects.
        /// </summary>
        internal static string InspectableItemDefects {
            get {
                return ResourceManager.GetString("InspectableItemDefects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date:.
        /// </summary>
        internal static string InspectableItemEndDate {
            get {
                return ResourceManager.GetString("InspectableItemEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect.
        /// </summary>
        internal static string InspectableItemInspect {
            get {
                return ResourceManager.GetString("InspectableItemInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenticel.
        /// </summary>
        internal static string InspectableItemLenticel {
            get {
                return ResourceManager.GetString("InspectableItemLenticel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin:.
        /// </summary>
        internal static string InspectableItemOrigin {
            get {
                return ResourceManager.GetString("InspectableItemOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack Date:.
        /// </summary>
        internal static string InspectableItemPackDate {
            get {
                return ResourceManager.GetString("InspectableItemPackDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packer:.
        /// </summary>
        internal static string InspectableItemPacker {
            get {
                return ResourceManager.GetString("InspectableItemPacker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Date.
        /// </summary>
        internal static string InspectableItemPastDate {
            get {
                return ResourceManager.GetString("InspectableItemPastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Inspection.
        /// </summary>
        internal static string InspectableItemPastInspection {
            get {
                return ResourceManager.GetString("InspectableItemPastInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string InspectableItemSave {
            get {
                return ResourceManager.GetString("InspectableItemSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string InspectableItemsEndDateLabel {
            get {
                return ResourceManager.GetString("InspectableItemsEndDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string InspectableItemsIdLabel {
            get {
                return ResourceManager.GetString("InspectableItemsIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        internal static string InspectableItemSize {
            get {
                return ResourceManager.GetString("InspectableItemSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples to Inspect.
        /// </summary>
        internal static string InspectableItemsLabel1 {
            get {
                return ResourceManager.GetString("InspectableItemsLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Country Of Origin.
        /// </summary>
        internal static string InspectableItemsPicker1 {
            get {
                return ResourceManager.GetString("InspectableItemsPicker1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string InspectableItemsStartDateLabel {
            get {
                return ResourceManager.GetString("InspectableItemsStartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        internal static string InspectableItemStage {
            get {
                return ResourceManager.GetString("InspectableItemStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspectable Items.
        /// </summary>
        internal static string InspectableItemsTitle {
            get {
                return ResourceManager.GetString("InspectableItemsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string InspectableItemSummary {
            get {
                return ResourceManager.GetString("InspectableItemSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample#.
        /// </summary>
        internal static string InspectableItemTitle {
            get {
                return ResourceManager.GetString("InspectableItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading...
        /// </summary>
        internal static string Loading1 {
            get {
                return ResourceManager.GetString("Loading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string LoginPageButton1 {
            get {
                return ResourceManager.GetString("LoginPageButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string LoginPageDisplayAlertMsg1 {
            get {
                return ResourceManager.GetString("LoginPageDisplayAlertMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Username/Password or Location not Selected..
        /// </summary>
        internal static string LoginPageDisplayAlertMsg2 {
            get {
                return ResourceManager.GetString("LoginPageDisplayAlertMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string LoginPageDisplayAlertMsg3 {
            get {
                return ResourceManager.GetString("LoginPageDisplayAlertMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string LoginPageEntry1 {
            get {
                return ResourceManager.GetString("LoginPageEntry1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPageEntry2 {
            get {
                return ResourceManager.GetString("LoginPageEntry2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissionPro.
        /// </summary>
        internal static string LoginPageLabel1 {
            get {
                return ResourceManager.GetString("LoginPageLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string LoginPagePicker1 {
            get {
                return ResourceManager.GetString("LoginPagePicker1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        internal static string LoginPagePicker2 {
            get {
                return ResourceManager.GetString("LoginPagePicker2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample #.
        /// </summary>
        internal static string SearchBar1 {
            get {
                return ResourceManager.GetString("SearchBar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Home.
        /// </summary>
        internal static string SettingsPageButton1 {
            get {
                return ResourceManager.GetString("SettingsPageButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Page.
        /// </summary>
        internal static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTabbedPageTitle {
            get {
                return ResourceManager.GetString("SettingsTabbedPageTitle", resourceCulture);
            }
        }
    }
}
