//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShelfLifeApp {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShelfLifeApp.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string AddEditPageButton1 {
            get {
                return ResourceManager.GetString("AddEditPageButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growers.
        /// </summary>
        internal static string AddEditPageEntry1 {
            get {
                return ResourceManager.GetString("AddEditPageEntry1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet #.
        /// </summary>
        internal static string AddEditPageEntry2 {
            get {
                return ResourceManager.GetString("AddEditPageEntry2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COO.
        /// </summary>
        internal static string AddEditPagePicker1 {
            get {
                return ResourceManager.GetString("AddEditPagePicker1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packers.
        /// </summary>
        internal static string AddEditPagePicker2 {
            get {
                return ResourceManager.GetString("AddEditPagePicker2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        internal static string AddEditPagePicker3 {
            get {
                return ResourceManager.GetString("AddEditPagePicker3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string AddEditPagePicker4 {
            get {
                return ResourceManager.GetString("AddEditPagePicker4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sample.
        /// </summary>
        internal static string AddEditPageTitle {
            get {
                return ResourceManager.GetString("AddEditPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start New Sample.
        /// </summary>
        internal static string HomePageButton1 {
            get {
                return ResourceManager.GetString("HomePageButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissionPro.
        /// </summary>
        internal static string HomeTabbedPageTitle {
            get {
                return ResourceManager.GetString("HomeTabbedPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string HomeTabbedPageToolbarItem1 {
            get {
                return ResourceManager.GetString("HomeTabbedPageToolbarItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        internal static string HomeTabbedPageToolbarItem2 {
            get {
                return ResourceManager.GetString("HomeTabbedPageToolbarItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading...
        /// </summary>
        internal static string Loading1 {
            get {
                return ResourceManager.GetString("Loading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string LoginPageButton1 {
            get {
                return ResourceManager.GetString("LoginPageButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string LoginPageDisplayAlertMsg1 {
            get {
                return ResourceManager.GetString("LoginPageDisplayAlertMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Username/Password or Location not Selected..
        /// </summary>
        internal static string LoginPageDisplayAlertMsg2 {
            get {
                return ResourceManager.GetString("LoginPageDisplayAlertMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string LoginPageDisplayAlertMsg3 {
            get {
                return ResourceManager.GetString("LoginPageDisplayAlertMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string LoginPageEntry1 {
            get {
                return ResourceManager.GetString("LoginPageEntry1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPageEntry2 {
            get {
                return ResourceManager.GetString("LoginPageEntry2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissionPro Sign In.
        /// </summary>
        internal static string LoginPageLabel1 {
            get {
                return ResourceManager.GetString("LoginPageLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string LoginPagePicker1 {
            get {
                return ResourceManager.GetString("LoginPagePicker1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample #.
        /// </summary>
        internal static string SearchBar1 {
            get {
                return ResourceManager.GetString("SearchBar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Home.
        /// </summary>
        internal static string SettingsPageButton1 {
            get {
                return ResourceManager.GetString("SettingsPageButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Page.
        /// </summary>
        internal static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTabbedPageTitle {
            get {
                return ResourceManager.GetString("SettingsTabbedPageTitle", resourceCulture);
            }
        }
    }
}
